CREATE TABLE Jobs (
    JobID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Company VARCHAR(255) NOT NULL,
    Description TEXT,
    Location VARCHAR(255),
    PostedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);